### ISSUE TITLE
Unneeded code?

### ISSUE THREAD

**Issue by kaluzaklein** [thushv89/exercises_thushv_dot_com#3]
There are a couple of peculiar 'if' statements that I would like to be checked for accuracy (they don't appear to do anything):

```
                if sent_text[self._cursor[b]]!=src_dictionary['<s>']:
                    batch_data[b] = sent_text[self._cursor[b]]
                else:
                    batch_data[b] = sent_text[self._cursor[b]]

            if self._is_source:
                data, labels = self.next_batch(self._sent_ids, False)
            else:
                data, labels = self.next_batch(self._sent_ids, False)
```

**Comment by thushv89** [comment]
Hi @kaluzaklein ,

Apologies about the "extreme" delay. To answer your questions,

if sent_text[self._cursor[b]]!=src_dictionary['<s>']:
      batch_data[b] = sent_text[self._cursor[b]]

is there to stop using the embedding for the token <s> from both target and source embeddings. But over the time, it seems the condition became obsolete. I'll remove that and update the code.

if self._is_source:
       data, labels = self.next_batch(self._sent_ids, False)
else:
        data, labels = self.next_batch(self._sent_ids, False)

is also redundant. I'll update accordingly. Thanks for spotting both of them.
