### ISSUE TITLE
 Inference – How to generate translations, after i have a Model ?

### ISSUE THREAD

**Issue by vhuytdt** [thushv89/exercises_thushv_dot_com#4]
how to inference - with your model

**Comment by thushv89** [comment]
Hi @vhuytdt ,

Apologies about the delay. The inference process is as follows.

1. You feed in the source sentence to the encoder. 
2. After the sentence has reached the end of the encoder, you feed in a single `<s>` token to the decoder
3. Then you get the prediction made by the decoder for <s> token,
4. You keep using the previous output of the decoder as the next input until you get a `</s>` token
